### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by DanielBlupi** [optix2000/totsugeki#27] opened 2021-08-08 19:10 UTC
![totsugekierror](https://user-images.githubusercontent.com/22030177/128643153-0da779f9-e938-44e0-8e11-60ae8854c6df.jpg)

**Comment by optix2000** [comment] 2021-08-08 21:35
Looks like a duplicate of #23

Use the stable version of totsugeki (v1.1.1 at time of writing) instead of the beta version (v1.1.2).

**Closed by optix2000** 2021-08-08 21:35 UTC
Labels: bug, duplicate
