### ISSUE TITLE
Going back to the main menu from a lobby kills matches

### ISSUE THREAD

**Issue by Kaanibaru** [optix2000/totsugeki#19] opened 2021-07-30 22:53 UTC
Hey! 

I've been using Totsugeki with no issues but one, whenever I return to the main menu and join another lobby/park/floor every duel station starts saying "Failed to connect to the Duel Station" or something along those lines.
I can still access lobbies, rankings and everything else, I just can't connect to matches after leaving another lobby.

I don't have this issue without Totsugeki and rebooting the game seems to fix it (luckily it's super fast now). 
Not sure what the issue can be or if it is even on the mod's end at all, I don't have any special message in the command prompt either so not sure where it could come from.

Anyways thanks for the awesome mod, you're making a godlike job!

**Comment by optix2000** [comment] 2021-07-30 23:36
> I return to the main menu and join another lobby/park/floor every duel station starts saying "Failed to connect to the Duel Station" or something along those lines.

I've actually encountered this prior to writing Totsugeki, but haven't run into it recently. If you can screenshot or paste the logs from Totsugeki right after you see that message it will help me see what's going on.

I'm somewhat doubtful it's due to Totsugeki, but the logs will help confirm what's going on. If it's a server-side issue, the logs will help me see if there's way for Totsugeki to work around it.

> Anyways thanks for the awesome mod, you're making a godlike job!

Glad you find it useful!

**Comment by Kaanibaru** [comment] 2021-07-31 03:31
Well apparently the issue only pops up when I leave the "News" tab open after joining a lobby, when I close it the stations start working again and the issue disappears entirely... :|

Otherwise whenever I run into that issue I get a neverending passive stream of this in the logs https://b.catgirlsare.sexy/r-rP_3CIWceV.png no idea if that's even useful but they don't seem to appear at all when lobbies are working as intended. 

I guess it might just be some Strive server fuckery but who knows, at least if someone also runs into that issue just know that pressing a single button fixes it

**Comment by optix2000** [comment] 2021-07-31 10:57
That's interesting. Looks like maybe an endless loop in GGST. Maybe Totsugeki can work around this problem if `/api/tus/read` is a cacheable response.

I'll see if I can reproduce it on my side. To confirm, what are the steps you take for the issue to happen?

**Comment by Kaanibaru** [comment] 2021-08-01 23:58
1/ Launch GGST with Totsugeki
2/ Network -> Online Match
3/ Select a lobby/floor
4/ Everything works
5/ Leave back to main menu
6/ Network -> Online Match
7/ Select a lobby/floor
8/ "Failed to obtain Duel Station information."

I think that's about it, thank you for looking into it!

**Comment by Avre** [comment] 2021-08-02 01:05
I just tried the above steps and did not have this issue.

**Comment by Kaanibaru** [comment] 2021-08-02 01:15
Might just be on my end then, I'm able to reproduce this consistently.

**Comment by optix2000** [comment] 2021-08-03 06:17
I just tried this tonight and could not reproduce. When this happens does this happen on _all_ duel stations? Sometimes the ones near the entrance bug out.

**Comment by Kaanibaru** [comment] 2021-08-03 21:26
It happens on all duel stations and never fixes itself, it always happens when the news tab in lobbies doesn't load any information, also leaves the "wifi" loading indefinitely.
I also get this issue when I join a lobby after checking the rankings in the main menu.

Weird but I guess I'm just unlucky, I'll try it out on a different PC :|

**Comment by optix2000** [comment] 2021-08-04 00:50
Let me try blocking the news API to simulate your situation. I suspect that GGST is only allowed to make one API request at a time, so the duel station ones are backed up behind waiting for news to load.

**Comment by optix2000** [comment] 2021-08-07 01:47
Try the [latest release](https://github.com/optix2000/totsugeki/releases/latest) I'm hoping the timeouts may help here if a connection is getting stuck.

**Comment by optix2000** [comment] 2021-08-08 21:42
Closing for now. Let me know if this is still happening.

**Closed by optix2000** 2021-08-08 21:42 UTC
Labels: bug, needs more info
