### ISSUE TITLE
Fatal error on startup (1.3.0)

### ISSUE THREAD

**Issue by ThunderDong** [optix2000/totsugeki#49] opened 2021-08-31 16:47 UTC
I get a fatal error on startup (I provided a screenshot of the error log below). It happens about 80% of the time. Not sure what triggers it but it could have something to do with the fact that I have GGST installed on my D: drive instead of my C: drive. It has occurred regardless of whether I use unga bunga arguments or not.

**Does this issue happen when you don't use Totsugeki?**
No

**Totsugeki Version and logs**

Version: 1.3.0
Error log screenshot: 
![Untitled](https://user-images.githubusercontent.com/35617173/131543312-c44b45f9-9696-4d81-9c7e-9b2dfb3206b8.png)

**Steps to Reproduce**

1. Launch totsugeki
2. Wait until GGST process launches
3. ????
4. Profit

**Comment by dons20** [comment] 2021-08-31 17:45
It shouldn't be related to your storage device. I have GG Strive on `E` and Totsugeki on `C`

**Comment by optix2000** [comment] 2021-08-31 21:54
This is a dupe of #34.

For now, you can launch Totsugeki after you launch GGST as a workaround.

**Closed** 2021-08-31 21:54 UTC
Labels: bug, duplicate
